# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 258)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Set_wavelength = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Set_wavelength.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.Set_wavelength.setDecimals(6)
        self.Set_wavelength.setMinimum(0.0)
        self.Set_wavelength.setMaximum(400.0)
        self.Set_wavelength.setSingleStep(1e-05)
        self.Set_wavelength.setProperty("value", 396.959185)
        self.Set_wavelength.setObjectName("Set_wavelength")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.label.setObjectName("label")
        self.lcdnumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdnumber.setGeometry(QtCore.QRect(20, 120, 161, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdnumber.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lcdnumber.setFont(font)
        self.lcdnumber.setSmallDecimalPoint(False)
        self.lcdnumber.setDigitCount(10)
        self.lcdnumber.setObjectName("lcdnumber")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(100, 160, 75, 23))
        self.stop_button.setObjectName("stop_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 10, 31, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(250, 10, 201, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(100, 120, 61, 21))
        self.label_7.setObjectName("label_7")
        self.dc_offset_vertical = QtWidgets.QDoubleSpinBox(self.tab)
        self.dc_offset_vertical.setGeometry(QtCore.QRect(20, 140, 62, 22))
        self.dc_offset_vertical.setDecimals(1)
        self.dc_offset_vertical.setMinimum(-100.0)
        self.dc_offset_vertical.setObjectName("dc_offset_vertical")
        self.ec_voltage_1 = QtWidgets.QDoubleSpinBox(self.tab)
        self.ec_voltage_1.setGeometry(QtCore.QRect(20, 60, 62, 22))
        self.ec_voltage_1.setDecimals(1)
        self.ec_voltage_1.setMinimum(-10.0)
        self.ec_voltage_1.setMaximum(10.0)
        self.ec_voltage_1.setSingleStep(0.1)
        self.ec_voltage_1.setProperty("value", 2.0)
        self.ec_voltage_1.setObjectName("ec_voltage_1")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 51, 21))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 91, 21))
        self.label_4.setObjectName("label_4")
        self.dc_offset_horizontal = QtWidgets.QDoubleSpinBox(self.tab)
        self.dc_offset_horizontal.setGeometry(QtCore.QRect(100, 140, 62, 22))
        self.dc_offset_horizontal.setDecimals(1)
        self.dc_offset_horizontal.setMinimum(-100.0)
        self.dc_offset_horizontal.setObjectName("dc_offset_horizontal")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 51, 21))
        self.label_3.setObjectName("label_3")
        self.ec_voltage_2 = QtWidgets.QDoubleSpinBox(self.tab)
        self.ec_voltage_2.setGeometry(QtCore.QRect(100, 60, 62, 22))
        self.ec_voltage_2.setDecimals(1)
        self.ec_voltage_2.setMinimum(-10.0)
        self.ec_voltage_2.setMaximum(10.0)
        self.ec_voltage_2.setSingleStep(0.1)
        self.ec_voltage_2.setProperty("value", 2.0)
        self.ec_voltage_2.setObjectName("ec_voltage_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 141, 21))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pic_control_p = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.pic_control_p.setGeometry(QtCore.QRect(20, 80, 62, 22))
        self.pic_control_p.setDecimals(1)
        self.pic_control_p.setMinimum(-10.0)
        self.pic_control_p.setMaximum(10.0)
        self.pic_control_p.setSingleStep(0.1)
        self.pic_control_p.setProperty("value", 0.5)
        self.pic_control_p.setObjectName("pic_control_p")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(50, 60, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(80, 40, 51, 21))
        self.label_9.setObjectName("label_9")
        self.pic_control_i = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.pic_control_i.setGeometry(QtCore.QRect(100, 80, 62, 22))
        self.pic_control_i.setDecimals(5)
        self.pic_control_i.setMinimum(-10.0)
        self.pic_control_i.setMaximum(10.0)
        self.pic_control_i.setSingleStep(0.0001)
        self.pic_control_i.setProperty("value", 0.00425)
        self.pic_control_i.setObjectName("pic_control_i")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(110, 60, 21, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.PID_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.PID_check_box.setGeometry(QtCore.QRect(60, 200, 81, 17))
        self.PID_check_box.setObjectName("PID_check_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Set wavelength"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Current wavelength"))
        self.label_7.setText(_translate("MainWindow", "horizontal"))
        self.label_6.setText(_translate("MainWindow", "vertical"))
        self.label_4.setText(_translate("MainWindow", "Endcaps (V)"))
        self.label_3.setText(_translate("MainWindow", "Voltages"))
        self.label_5.setText(_translate("MainWindow", "Offset voltage (10 mV)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "DC offset"))
        self.label_8.setText(_translate("MainWindow", "P"))
        self.label_9.setText(_translate("MainWindow", "PID"))
        self.label_10.setText(_translate("MainWindow", "I"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PID"))
        self.PID_check_box.setText(_translate("MainWindow", "PID Stopper"))

