# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(1850, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gui.sizePolicy().hasHeightForWidth())
        gui.setSizePolicy(sizePolicy)
        gui.setMinimumSize(QtCore.QSize(1850, 1000))
        gui.setMaximumSize(QtCore.QSize(1850, 1000))
        self.centralWidget = QtWidgets.QWidget(gui)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalFrame = QtWidgets.QFrame(self.tab)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame1 = QtWidgets.QFrame(self.verticalFrame)
        self.verticalFrame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalFrame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.CamConnectButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.CamConnectButton.setObjectName("CamConnectButton")
        self.verticalLayout_3.addWidget(self.CamConnectButton)
        self.CamDisconnectButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.CamDisconnectButton.setObjectName("CamDisconnectButton")
        self.verticalLayout_3.addWidget(self.CamDisconnectButton)
        self.CamStartButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.CamStartButton.setObjectName("CamStartButton")
        self.verticalLayout_3.addWidget(self.CamStartButton)
        self.CamStopButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.CamStopButton.setObjectName("CamStopButton")
        self.verticalLayout_3.addWidget(self.CamStopButton)
        self.BackgroundButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.BackgroundButton.setObjectName("BackgroundButton")
        self.verticalLayout_3.addWidget(self.BackgroundButton)
        self.ExpTimeSB = QtWidgets.QDoubleSpinBox(self.verticalFrame1)
        self.ExpTimeSB.setDecimals(4)
        self.ExpTimeSB.setMinimum(0.0001)
        self.ExpTimeSB.setMaximum(5.0)
        self.ExpTimeSB.setSingleStep(0.1)
        self.ExpTimeSB.setObjectName("ExpTimeSB")
        self.verticalLayout_3.addWidget(self.ExpTimeSB)
        self.ExpTimeButton = QtWidgets.QPushButton(self.verticalFrame1)
        self.ExpTimeButton.setObjectName("ExpTimeButton")
        self.verticalLayout_3.addWidget(self.ExpTimeButton)
        self.BackgroundCheckBox = QtWidgets.QCheckBox(self.verticalFrame1)
        self.BackgroundCheckBox.setObjectName("BackgroundCheckBox")
        self.verticalLayout_3.addWidget(self.BackgroundCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalFrame1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.BinComboBox = QtWidgets.QComboBox(self.verticalFrame1)
        self.BinComboBox.setObjectName("BinComboBox")
        self.BinComboBox.addItem("")
        self.BinComboBox.addItem("")
        self.BinComboBox.addItem("")
        self.BinComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.BinComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.verticalFrame1)
        self.SaveCB = QtWidgets.QCheckBox(self.verticalFrame)
        self.SaveCB.setObjectName("SaveCB")
        self.verticalLayout.addWidget(self.SaveCB)
        self.verticalFrame_2 = QtWidgets.QFrame(self.verticalFrame)
        self.verticalFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.MotorHomeButton = QtWidgets.QPushButton(self.verticalFrame_2)
        self.MotorHomeButton.setObjectName("MotorHomeButton")
        self.verticalLayout_6.addWidget(self.MotorHomeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.RefreshTrapButton = QtWidgets.QPushButton(self.verticalFrame_2)
        self.RefreshTrapButton.setObjectName("RefreshTrapButton")
        self.verticalLayout_6.addWidget(self.RefreshTrapButton)
        self.ClearPlotButton = QtWidgets.QPushButton(self.verticalFrame_2)
        self.ClearPlotButton.setObjectName("ClearPlotButton")
        self.verticalLayout_6.addWidget(self.ClearPlotButton)
        self.verticalLayout.addWidget(self.verticalFrame_2)
        self.horizontalLayout_3.addWidget(self.verticalFrame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ImageLayout = QtWidgets.QVBoxLayout()
        self.ImageLayout.setSpacing(6)
        self.ImageLayout.setObjectName("ImageLayout")
        self.verticalLayout_5.addLayout(self.ImageLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ROIStdLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ROIStdLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROIStdLineEdit.setObjectName("ROIStdLineEdit")
        self.gridLayout_3.addWidget(self.ROIStdLineEdit, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.PlotMeanLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PlotMeanLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PlotMeanLineEdit.setObjectName("PlotMeanLineEdit")
        self.gridLayout_3.addWidget(self.PlotMeanLineEdit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 4, 1, 1)
        self.ROIMeanLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ROIMeanLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROIMeanLineEdit.setObjectName("ROIMeanLineEdit")
        self.gridLayout_3.addWidget(self.ROIMeanLineEdit, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.ROIx0L = QtWidgets.QLineEdit(self.frame)
        self.ROIx0L.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ROIx0L.setObjectName("ROIx0L")
        self.gridLayout_3.addWidget(self.ROIx0L, 0, 2, 1, 1)
        self.ROIxdL = QtWidgets.QLineEdit(self.frame)
        self.ROIxdL.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ROIxdL.setObjectName("ROIxdL")
        self.gridLayout_3.addWidget(self.ROIxdL, 0, 3, 1, 1)
        self.ROIy0L = QtWidgets.QLineEdit(self.frame)
        self.ROIy0L.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ROIy0L.setObjectName("ROIy0L")
        self.gridLayout_3.addWidget(self.ROIy0L, 0, 4, 1, 1)
        self.ROIydL = QtWidgets.QLineEdit(self.frame)
        self.ROIydL.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ROIydL.setObjectName("ROIydL")
        self.gridLayout_3.addWidget(self.ROIydL, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.EndcapOffsetAsb = QtWidgets.QDoubleSpinBox(self.frame)
        self.EndcapOffsetAsb.setDecimals(3)
        self.EndcapOffsetAsb.setMinimum(-5.0)
        self.EndcapOffsetAsb.setMaximum(5.0)
        self.EndcapOffsetAsb.setSingleStep(0.1)
        self.EndcapOffsetAsb.setObjectName("EndcapOffsetAsb")
        self.gridLayout_3.addWidget(self.EndcapOffsetAsb, 2, 1, 1, 1)
        self.EndcapOffsetBsb = QtWidgets.QDoubleSpinBox(self.frame)
        self.EndcapOffsetBsb.setDecimals(3)
        self.EndcapOffsetBsb.setMinimum(-5.0)
        self.EndcapOffsetBsb.setMaximum(5.0)
        self.EndcapOffsetBsb.setSingleStep(0.1)
        self.EndcapOffsetBsb.setObjectName("EndcapOffsetBsb")
        self.gridLayout_3.addWidget(self.EndcapOffsetBsb, 2, 2, 1, 1)
        self.EndcapSetButton = QtWidgets.QPushButton(self.frame)
        self.EndcapSetButton.setObjectName("EndcapSetButton")
        self.gridLayout_3.addWidget(self.EndcapSetButton, 2, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PlotLayout_2f = QtWidgets.QFrame(self.frame)
        self.PlotLayout_2f.setMaximumSize(QtCore.QSize(600, 220))
        self.PlotLayout_2f.setFrameShape(QtWidgets.QFrame.Panel)
        self.PlotLayout_2f.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PlotLayout_2f.setObjectName("PlotLayout_2f")
        self.PlotLayout = QtWidgets.QVBoxLayout(self.PlotLayout_2f)
        self.PlotLayout.setContentsMargins(11, 11, 11, 11)
        self.PlotLayout.setSpacing(6)
        self.PlotLayout.setObjectName("PlotLayout")
        self.PlotLayout_2 = QtWidgets.QVBoxLayout()
        self.PlotLayout_2.setSpacing(6)
        self.PlotLayout_2.setObjectName("PlotLayout_2")
        self.PlotLayout.addLayout(self.PlotLayout_2)
        self.horizontalLayout_4.addWidget(self.PlotLayout_2f)
        self.PlotLayout_3f = QtWidgets.QFrame(self.frame)
        self.PlotLayout_3f.setMaximumSize(QtCore.QSize(600, 220))
        self.PlotLayout_3f.setFrameShape(QtWidgets.QFrame.Panel)
        self.PlotLayout_3f.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PlotLayout_3f.setObjectName("PlotLayout_3f")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PlotLayout_3f)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PlotLayout_3 = QtWidgets.QVBoxLayout()
        self.PlotLayout_3.setSpacing(6)
        self.PlotLayout_3.setObjectName("PlotLayout_3")
        self.verticalLayout_4.addLayout(self.PlotLayout_3)
        self.horizontalLayout_4.addWidget(self.PlotLayout_3f)
        self.verticalFrame_3 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_3.setMaximumSize(QtCore.QSize(600, 220))
        self.verticalFrame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PlotLayout_4 = QtWidgets.QVBoxLayout()
        self.PlotLayout_4.setSpacing(6)
        self.PlotLayout_4.setObjectName("PlotLayout_4")
        self.verticalLayout_7.addLayout(self.PlotLayout_4)
        self.horizontalLayout_4.addWidget(self.verticalFrame_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1850, 21))
        self.menuBar.setObjectName("menuBar")
        gui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(gui)
        self.mainToolBar.setObjectName("mainToolBar")
        gui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(gui)
        self.statusBar.setObjectName("statusBar")
        gui.setStatusBar(self.statusBar)

        self.retranslateUi(gui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "gui"))
        self.label_7.setText(_translate("gui", "Camera"))
        self.CamConnectButton.setText(_translate("gui", "Connect"))
        self.CamDisconnectButton.setText(_translate("gui", "Disconnect"))
        self.CamStartButton.setText(_translate("gui", "Start"))
        self.CamStopButton.setText(_translate("gui", "Stop"))
        self.BackgroundButton.setText(_translate("gui", "Background"))
        self.ExpTimeButton.setText(_translate("gui", "set exptime"))
        self.BackgroundCheckBox.setText(_translate("gui", "Use BG"))
        self.label.setText(_translate("gui", "Binning"))
        self.BinComboBox.setItemText(0, _translate("gui", "1"))
        self.BinComboBox.setItemText(1, _translate("gui", "2"))
        self.BinComboBox.setItemText(2, _translate("gui", "4"))
        self.BinComboBox.setItemText(3, _translate("gui", "10"))
        self.SaveCB.setText(_translate("gui", "Save?!"))
        self.label_8.setText(_translate("gui", "Motor"))
        self.MotorHomeButton.setText(_translate("gui", "Go home!"))
        self.label_9.setText(_translate("gui", "Trap"))
        self.RefreshTrapButton.setText(_translate("gui", "Refresh Trap!"))
        self.ClearPlotButton.setText(_translate("gui", "ClearPlot"))
        self.label_3.setText(_translate("gui", "Mean"))
        self.label_2.setText(_translate("gui", "Plot Mean"))
        self.label_4.setText(_translate("gui", "Std"))
        self.label_5.setText(_translate("gui", "EL ROI"))
        self.label_6.setText(_translate("gui", "params: x0, xd, y0, yd"))
        self.label_10.setText(_translate("gui", "Endcap offset /V"))
        self.EndcapSetButton.setText(_translate("gui", "Set Offset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gui", "Tab 1"))
        self.pushButton.setText(_translate("gui", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gui", "Tab 2"))

